In [14]:
numbers = [1, 2, 3, 4, 5] #使用符號建立
mixed_list = [1, "Hello",3.14, True] #元素值可以不同資料類型
empty_list = []
list_from_range = list(range(10,21))
list_from_range

#list的操作
list_from_range[4] #subscript

14

In [15]:
range(5)
range(1,5)
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [16]:
my_list = list(range(1,10,2))

In [17]:
empty_list = []
empty_list.append(67)
empty_list.append(96)
empty_list

[67, 96]

In [29]:
pl = {'name':'徐國堂',
        'age':'40',
        'city':'Taipei'
      }
pl
print(pl=['name'])
print(pl.get('age'))

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (625709111.py, line 6)

In [33]:
fruits =['蘋果','香蕉','果子']
for fruit in fruits:
    print(fruit)

蘋果
香蕉
果子

In [34]:
for index,fruit in enumerate(fruits):
    print(index,fruit)
    print("================");

0 蘋果
================
1 香蕉
================
2 果子
================

In [38]:
=cities = {
    "Taipei": "台北",
    "New Taipei": "新北",
    "Taoyuan": "桃園",
    "Taichung": "台中",
    "Tainan": "台南",
    "Kaohsiung": "高雄",
    "Keelung": "基隆",
    "Hsinchu": "新竹",
    "Chiayi": "嘉義",
    "Hualien": "花蓮"
}
for key, value in cities.items();
    print(f"{key}: {

SyntaxError: invalid syntax (2988770007.py, line 1)

In [39]:
for i in range(50):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [51]:
import random
students = []
for i in range(1,51):
    students.append(
        {
            'name':f'student{i}',
            'chinese':random.randint(50,100),
            'english':random.randint(50,100),
            'math':5,
            'history':50,
            'health':50

        }
    )
 
students_str = str(students)
students_str

"[{'name': 'student1', 'chinese': 94, 'english': 62, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student2', 'chinese': 65, 'english': 92, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student3', 'chinese': 56, 'english': 56, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student4', 'chinese': 82, 'english': 53, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student5', 'chinese': 56, 'english': 92, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student6', 'chinese': 60, 'english': 63, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student7', 'chinese': 92, 'english': 53, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student8', 'chinese': 65, 'english': 81, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student9', 'chinese': 90, 'english': 54, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student10', 'chinese': 84, 'english': 79, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student11', 'chinese': 74, 'english': 80, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student12', 'chinese': 64, 'english': 86, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student13', 'chinese': 67, 'english': 70, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student14', 'chinese': 72, 'english': 83, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student15', 'chinese': 66, 'english': 55, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student16', 'chinese': 74, 'english': 79, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student17', 'chinese': 76, 'english': 55, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student18', 'chinese': 79, 'english': 62, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student19', 'chinese': 67, 'english': 64, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student20', 'chinese': 94, 'english': 56, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student21', 'chinese': 77, 'english': 65, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student22', 'chinese': 80, 'english': 97, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student23', 'chinese': 82, 'english': 73, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student24', 'chinese': 100, 'english': 62, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student25', 'chinese': 92, 'english': 98, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student26', 'chinese': 58, 'english': 66, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student27', 'chinese': 94, 'english': 90, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student28', 'chinese': 87, 'english': 68, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student29', 'chinese': 83, 'english': 72, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student30', 'chinese': 92, 'english': 77, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student31', 'chinese': 75, 'english': 83, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student32', 'chinese': 91, 'english': 96, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student33', 'chinese': 95, 'english': 78, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student34', 'chinese': 52, 'english': 97, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student35', 'chinese': 62, 'english': 93, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student36', 'chinese': 69, 'english': 82, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student37', 'chinese': 75, 'english': 54, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student38', 'chinese': 68, 'english': 56, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student39', 'chinese': 98, 'english': 51, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student40', 'chinese': 98, 'english': 81, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student41', 'chinese': 88, 'english': 68, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student42', 'chinese': 76, 'english': 64, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student43', 'chinese': 70, 'english': 74, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student44', 'chinese': 72, 'english': 87, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student45', 'chinese': 69, 'english': 89, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student46', 'chinese': 72, 'english': 50, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student47', 'chinese': 90, 'english': 72, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student48', 'chinese': 50, 'english': 76, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student49', 'chinese': 97, 'english': 63, 'math': 5, 'history': 50, 'health': 50}, {'name': 'student50', 'chinese': 97, 'english': 83, 'math': 5, 'history': 50, 'health': 50}]"

In [46]:
import random
students = []
for i in range(1,51):
    students.append(
        {
            'name':f'student{i}',
            'chinese':random.randint(50,100),
            'english':random.randint(50,100),
            'math':random.randint(50,100),
            'history':random.randint(50,100),
            'health':random.randint(50,100)
        }
    )

students

[{'name': 'student1',
  'chinese': 99,
  'english': 56,
  'math': 86,
  'history': 53,
  'health': 92},
 {'name': 'student2',
  'chinese': 76,
  'english': 77,
  'math': 70,
  'history': 63,
  'health': 93},
 {'name': 'student3',
  'chinese': 61,
  'english': 91,
  'math': 97,
  'history': 72,
  'health': 77},
 {'name': 'student4',
  'chinese': 90,
  'english': 65,
  'math': 52,
  'history': 54,
  'health': 77},
 {'name': 'student5',
  'chinese': 86,
  'english': 82,
  'math': 94,
  'history': 94,
  'health': 58},
 {'name': 'student6',
  'chinese': 67,
  'english': 100,
  'math': 68,
  'history': 59,
  'health': 93},
 {'name': 'student7',
  'chinese': 92,
  'english': 100,
  'math': 91,
  'history': 63,
  'health': 56},
 {'name': 'student8',
  'chinese': 82,
  'english': 92,
  'math': 79,
  'history': 50,
  'health': 93},
 {'name': 'student9',
  'chinese': 59,
  'english': 73,
  'math': 76,
  'history': 88,
  'health': 90},
 {'name': 'student10',
  'chinese': 80,
  'english': 63,
  'math': 79,
  'history': 100,
  'health': 89},
 {'name': 'student11',
  'chinese': 85,
  'english': 92,
  'math': 67,
  'history': 56,
  'health': 93},
 {'name': 'student12',
  'chinese': 81,
  'english': 89,
  'math': 73,
  'history': 52,
  'health': 94},
 {'name': 'student13',
  'chinese': 96,
  'english': 64,
  'math': 79,
  'history': 81,
  'health': 70},
 {'name': 'student14',
  'chinese': 98,
  'english': 62,
  'math': 86,
  'history': 70,
  'health': 65},
 {'name': 'student15',
  'chinese': 84,
  'english': 84,
  'math': 89,
  'history': 90,
  'health': 57},
 {'name': 'student16',
  'chinese': 77,
  'english': 69,
  'math': 78,
  'history': 98,
  'health': 88},
 {'name': 'student17',
  'chinese': 71,
  'english': 88,
  'math': 64,
  'history': 69,
  'health': 51},
 {'name': 'student18',
  'chinese': 74,
  'english': 52,
  'math': 70,
  'history': 89,
  'health': 75},
 {'name': 'student19',
  'chinese': 88,
  'english': 71,
  'math': 50,
  'history': 73,
  'health': 83},
 {'name': 'student20',
  'chinese': 52,
  'english': 50,
  'math': 98,
  'history': 58,
  'health': 88},
 {'name': 'student21',
  'chinese': 88,
  'english': 88,
  'math': 70,
  'history': 90,
  'health': 91},
 {'name': 'student22',
  'chinese': 94,
  'english': 98,
  'math': 98,
  'history': 92,
  'health': 86},
 {'name': 'student23',
  'chinese': 94,
  'english': 65,
  'math': 78,
  'history': 59,
  'health': 96},
 {'name': 'student24',
  'chinese': 92,
  'english': 68,
  'math': 50,
  'history': 70,
  'health': 79},
 {'name': 'student25',
  'chinese': 56,
  'english': 82,
  'math': 76,
  'history': 55,
  'health': 99},
 {'name': 'student26',
  'chinese': 91,
  'english': 84,
  'math': 64,
  'history': 57,
  'health': 55},
 {'name': 'student27',
  'chinese': 59,
  'english': 65,
  'math': 61,
  'history': 72,
  'health': 96},
 {'name': 'student28',
  'chinese': 88,
  'english': 99,
  'math': 60,
  'history': 63,
  'health': 81},
 {'name': 'student29',
  'chinese': 57,
  'english': 86,
  'math': 88,
  'history': 87,
  'health': 83},
 {'name': 'student30',
  'chinese': 66,
  'english': 97,
  'math': 57,
  'history': 75,
  'health': 98},
 {'name': 'student31',
  'chinese': 92,
  'english': 58,
  'math': 76,
  'history': 86,
  'health': 100},
 {'name': 'student32',
  'chinese': 97,
  'english': 95,
  'math': 89,
  'history': 96,
  'health': 80},
 {'name': 'student33',
  'chinese': 77,
  'english': 74,
  'math': 79,
  'history': 77,
  'health': 75},
 {'name': 'student34',
  'chinese': 63,
  'english': 94,
  'math': 76,
  'history': 98,
  'health': 97},
 {'name': 'student35',
  'chinese': 94,
  'english': 91,
  'math': 76,
  'history': 100,
  'health': 72},
 {'name': 'student36',
  'chinese': 92,
  'english': 93,
  'math': 78,
  'history': 90,
  'health': 78},
 {'name': 'student37',
  'chinese': 76,
  'english': 61,
  'math': 58,
  'history': 75,
  'health': 86},
 {'name': 'student38',
  'chinese': 68,
  'english': 70,
  'math': 99,
  'history': 96,
  'health': 74},
 {'name': 'student39',
  'chinese': 52,
  'english': 96,
  'math': 91,
  'history': 71,
  'health': 81},
 {'name': 'student40',
  'chinese': 91,
  'english': 55,
  'math': 61,
  'history': 88,
  'health': 55},
 {'name': 'student41',
  'chinese': 56,
  'english': 93,
  'math': 98,
  'history': 51,
  'health': 86},
 {'name': 'student42',
  'chinese': 75,
  'english': 83,
  'math': 88,
  'history': 86,
  'health': 100},
 {'name': 'student43',
  'chinese': 90,
  'english': 68,
  'math': 83,
  'history': 95,
  'health': 53},
 {'name': 'student44',
  'chinese': 65,
  'english': 84,
  'math': 65,
  'history': 75,
  'health': 71},
 {'name': 'student45',
  'chinese': 61,
  'english': 53,
  'math': 69,
  'history': 83,
  'health': 100},
 {'name': 'student46',
  'chinese': 67,
  'english': 51,
  'math': 86,
  'history': 94,
  'health': 55},
 {'name': 'student47',
  'chinese': 60,
  'english': 88,
  'math': 62,
  'history': 53,
  'health': 82},
 {'name': 'student48',
  'chinese': 68,
  'english': 86,
  'math': 74,
  'history': 63,
  'health': 59},
 {'name': 'student49',
  'chinese': 59,
  'english': 51,
  'math': 84,
  'history': 61,
  'health': 84},
 {'name': 'student50',
  'chinese': 81,
  'english': 85,
  'math': 100,
  'history': 73,
  'health': 76}]

In [52]:
# 將 students 列表轉換為字串
students_str = '\n'.join([
    f"姓名:{student['name']}, "
    f"國文:{student['chinese']}, "
    f"英文:{student['english']}, "
    f"數學:{student['math']}, "
    f"歷史:{student['history']}, "
    f"健康:{student['health']}"
    for student in students
])

print(students_str)

姓名:student1, 國文:94, 英文:62, 數學:5, 歷史:50, 健康:50
姓名:student2, 國文:65, 英文:92, 數學:5, 歷史:50, 健康:50
姓名:student3, 國文:56, 英文:56, 數學:5, 歷史:50, 健康:50
姓名:student4, 國文:82, 英文:53, 數學:5, 歷史:50, 健康:50
姓名:student5, 國文:56, 英文:92, 數學:5, 歷史:50, 健康:50
姓名:student6, 國文:60, 英文:63, 數學:5, 歷史:50, 健康:50
姓名:student7, 國文:92, 英文:53, 數學:5, 歷史:50, 健康:50
姓名:student8, 國文:65, 英文:81, 數學:5, 歷史:50, 健康:50
姓名:student9, 國文:90, 英文:54, 數學:5, 歷史:50, 健康:50
姓名:student10, 國文:84, 英文:79, 數學:5, 歷史:50, 健康:50
姓名:student11, 國文:74, 英文:80, 數學:5, 歷史:50, 健康:50
姓名:student12, 國文:64, 英文:86, 數學:5, 歷史:50, 健康:50
姓名:student13, 國文:67, 英文:70, 數學:5, 歷史:50, 健康:50
姓名:student14, 國文:72, 英文:83, 數學:5, 歷史:50, 健康:50
姓名:student15, 國文:66, 英文:55, 數學:5, 歷史:50, 健康:50
姓名:student16, 國文:74, 英文:79, 數學:5, 歷史:50, 健康:50
姓名:student17, 國文:76, 英文:55, 數學:5, 歷史:50, 健康:50
姓名:student18, 國文:79, 英文:62, 數學:5, 歷史:50, 健康:50
姓名:student19, 國文:67, 英文:64, 數學:5, 歷史:50, 健康:50
姓名:student20, 國文:94, 英文:56, 數學:5, 歷史:50, 健康:50
姓名:student21, 國文:77, 英文:65, 數學:5, 歷史:50, 健康:50
姓名:student22, 國文:80, 英文:97, 數學:5, 歷史:50, 健康:50
姓名:student23, 國文:82, 英文:73, 數學:5, 歷史:50, 健康:50
姓名:student24, 國文:100, 英文:62, 數學:5, 歷史:50, 健康:50
姓名:student25, 國文:92, 英文:98, 數學:5, 歷史:50, 健康:50
姓名:student26, 國文:58, 英文:66, 數學:5, 歷史:50, 健康:50
姓名:student27, 國文:94, 英文:90, 數學:5, 歷史:50, 健康:50
姓名:student28, 國文:87, 英文:68, 數學:5, 歷史:50, 健康:50
姓名:student29, 國文:83, 英文:72, 數學:5, 歷史:50, 健康:50
姓名:student30, 國文:92, 英文:77, 數學:5, 歷史:50, 健康:50
姓名:student31, 國文:75, 英文:83, 數學:5, 歷史:50, 健康:50
姓名:student32, 國文:91, 英文:96, 數學:5, 歷史:50, 健康:50
姓名:student33, 國文:95, 英文:78, 數學:5, 歷史:50, 健康:50
姓名:student34, 國文:52, 英文:97, 數學:5, 歷史:50, 健康:50
姓名:student35, 國文:62, 英文:93, 數學:5, 歷史:50, 健康:50
姓名:student36, 國文:69, 英文:82, 數學:5, 歷史:50, 健康:50
姓名:student37, 國文:75, 英文:54, 數學:5, 歷史:50, 健康:50
姓名:student38, 國文:68, 英文:56, 數學:5, 歷史:50, 健康:50
姓名:student39, 國文:98, 英文:51, 數學:5, 歷史:50, 健康:50
姓名:student40, 國文:98, 英文:81, 數學:5, 歷史:50, 健康:50
姓名:student41, 國文:88, 英文:68, 數學:5, 歷史:50, 健康:50
姓名:student42, 國文:76, 英文:64, 數學:5, 歷史:50, 健康:50
姓名:student43, 國文:70, 英文:74, 數學:5, 歷史:50, 健康:50
姓名:student44, 國文:72, 英文:87, 數學:5, 歷史:50, 健康:50
姓名:student45, 國文:69, 英文:89, 數學:5, 歷史:50, 健康:50
姓名:student46, 國文:72, 英文:50, 數學:5, 歷史:50, 健康:50
姓名:student47, 國文:90, 英文:72, 數學:5, 歷史:50, 健康:50
姓名:student48, 國文:50, 英文:76, 數學:5, 歷史:50, 健康:50
姓名:student49, 國文:97, 英文:63, 數學:5, 歷史:50, 健康:50
姓名:student50, 國文:97, 英文:83, 數學:5, 歷史:50, 健康:50

In [54]:
print(students_str,file=open('students.txt',mode='w',encoding='utf-8'))

In [3]:
file = open('students.csv', 'w', encoding="utf-8",newline='')
file.closed

False

In [4]:
import random
students = []
for i in range(1,51):
    students.append(
        {
            'name':f'student{i}',
            'chinese':random.randint(50,100),
            'english':random.randint(50,100),
            'math':random.randint(50,100),
            'history':random.randint(50,100),
            'health':random.randint(50,100)
        }
    )
students

[{'name': 'student1',
  'chinese': 53,
  'english': 65,
  'math': 78,
  'history': 53,
  'health': 76},
 {'name': 'student2',
  'chinese': 81,
  'english': 54,
  'math': 76,
  'history': 76,
  'health': 99},
 {'name': 'student3',
  'chinese': 92,
  'english': 79,
  'math': 87,
  'history': 85,
  'health': 88},
 {'name': 'student4',
  'chinese': 90,
  'english': 73,
  'math': 86,
  'history': 66,
  'health': 56},
 {'name': 'student5',
  'chinese': 86,
  'english': 86,
  'math': 61,
  'history': 78,
  'health': 88},
 {'name': 'student6',
  'chinese': 90,
  'english': 74,
  'math': 64,
  'history': 95,
  'health': 67},
 {'name': 'student7',
  'chinese': 70,
  'english': 91,
  'math': 87,
  'history': 77,
  'health': 85},
 {'name': 'student8',
  'chinese': 86,
  'english': 85,
  'math': 99,
  'history': 57,
  'health': 70},
 {'name': 'student9',
  'chinese': 51,
  'english': 95,
  'math': 74,
  'history': 71,
  'health': 62},
 {'name': 'student10',
  'chinese': 53,
  'english': 58,
  'math': 94,
  'history': 71,
  'health': 78},
 {'name': 'student11',
  'chinese': 57,
  'english': 54,
  'math': 65,
  'history': 76,
  'health': 92},
 {'name': 'student12',
  'chinese': 83,
  'english': 59,
  'math': 81,
  'history': 74,
  'health': 76},
 {'name': 'student13',
  'chinese': 75,
  'english': 76,
  'math': 64,
  'history': 95,
  'health': 89},
 {'name': 'student14',
  'chinese': 80,
  'english': 94,
  'math': 73,
  'history': 81,
  'health': 68},
 {'name': 'student15',
  'chinese': 67,
  'english': 52,
  'math': 63,
  'history': 86,
  'health': 98},
 {'name': 'student16',
  'chinese': 54,
  'english': 93,
  'math': 73,
  'history': 73,
  'health': 79},
 {'name': 'student17',
  'chinese': 97,
  'english': 95,
  'math': 96,
  'history': 75,
  'health': 80},
 {'name': 'student18',
  'chinese': 65,
  'english': 68,
  'math': 87,
  'history': 53,
  'health': 67},
 {'name': 'student19',
  'chinese': 67,
  'english': 91,
  'math': 75,
  'history': 55,
  'health': 66},
 {'name': 'student20',
  'chinese': 71,
  'english': 96,
  'math': 89,
  'history': 91,
  'health': 56},
 {'name': 'student21',
  'chinese': 66,
  'english': 83,
  'math': 98,
  'history': 85,
  'health': 73},
 {'name': 'student22',
  'chinese': 54,
  'english': 88,
  'math': 65,
  'history': 59,
  'health': 71},
 {'name': 'student23',
  'chinese': 88,
  'english': 92,
  'math': 69,
  'history': 78,
  'health': 77},
 {'name': 'student24',
  'chinese': 96,
  'english': 57,
  'math': 76,
  'history': 85,
  'health': 86},
 {'name': 'student25',
  'chinese': 74,
  'english': 84,
  'math': 56,
  'history': 93,
  'health': 68},
 {'name': 'student26',
  'chinese': 89,
  'english': 97,
  'math': 68,
  'history': 95,
  'health': 53},
 {'name': 'student27',
  'chinese': 68,
  'english': 96,
  'math': 96,
  'history': 100,
  'health': 72},
 {'name': 'student28',
  'chinese': 59,
  'english': 66,
  'math': 87,
  'history': 54,
  'health': 54},
 {'name': 'student29',
  'chinese': 97,
  'english': 67,
  'math': 51,
  'history': 63,
  'health': 84},
 {'name': 'student30',
  'chinese': 95,
  'english': 51,
  'math': 53,
  'history': 60,
  'health': 53},
 {'name': 'student31',
  'chinese': 67,
  'english': 100,
  'math': 70,
  'history': 91,
  'health': 64},
 {'name': 'student32',
  'chinese': 67,
  'english': 72,
  'math': 56,
  'history': 67,
  'health': 84},
 {'name': 'student33',
  'chinese': 68,
  'english': 59,
  'math': 82,
  'history': 60,
  'health': 57},
 {'name': 'student34',
  'chinese': 73,
  'english': 63,
  'math': 84,
  'history': 73,
  'health': 59},
 {'name': 'student35',
  'chinese': 71,
  'english': 60,
  'math': 78,
  'history': 51,
  'health': 95},
 {'name': 'student36',
  'chinese': 91,
  'english': 90,
  'math': 71,
  'history': 59,
  'health': 67},
 {'name': 'student37',
  'chinese': 52,
  'english': 97,
  'math': 74,
  'history': 83,
  'health': 74},
 {'name': 'student38',
  'chinese': 98,
  'english': 68,
  'math': 65,
  'history': 88,
  'health': 96},
 {'name': 'student39',
  'chinese': 54,
  'english': 64,
  'math': 81,
  'history': 60,
  'health': 62},
 {'name': 'student40',
  'chinese': 88,
  'english': 100,
  'math': 50,
  'history': 69,
  'health': 81},
 {'name': 'student41',
  'chinese': 82,
  'english': 83,
  'math': 83,
  'history': 81,
  'health': 65},
 {'name': 'student42',
  'chinese': 74,
  'english': 53,
  'math': 95,
  'history': 81,
  'health': 53},
 {'name': 'student43',
  'chinese': 76,
  'english': 97,
  'math': 78,
  'history': 59,
  'health': 50},
 {'name': 'student44',
  'chinese': 70,
  'english': 73,
  'math': 88,
  'history': 87,
  'health': 56},
 {'name': 'student45',
  'chinese': 94,
  'english': 65,
  'math': 94,
  'history': 76,
  'health': 54},
 {'name': 'student46',
  'chinese': 80,
  'english': 62,
  'math': 64,
  'history': 99,
  'health': 95},
 {'name': 'student47',
  'chinese': 50,
  'english': 92,
  'math': 89,
  'history': 99,
  'health': 78},
 {'name': 'student48',
  'chinese': 93,
  'english': 77,
  'math': 77,
  'history': 98,
  'health': 51},
 {'name': 'student49',
  'chinese': 66,
  'english': 52,
  'math': 76,
  'history': 96,
  'health': 53},
 {'name': 'student50',
  'chinese': 61,
  'english': 70,
  'math': 95,
  'history': 89,
  'health': 84}]

In [5]:
import csv

file = open('student.csv',mode='w',encoding='utf-8',newline='')
writer =csv.DictWriter(file,["name","chinese","english","math","history","health"])
#print(type(writer))
writer.writeheader()
writer.writerows(students)

file.close()
#file.closed